### ISSUE TITLE
Minimal example does not work

### ISSUE THREAD

**Issue by whacked** [xiaoxinghu/orgajs#7]
The minimal example on https://github.com/xiaoxinghu/orgajs/tree/master/examples/example

repro on node `10.6.0`:

```bash
mkdir /tmp/orga-test
cd /tmp/orga-test
yarn add orga-unified oast-to-hast unified to-vfile vfile-reporter rehype-document rehype-stringify

cat > test.js <<EOF
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var parse = require('orga-unified')
var mutate = require('oast-to-hast')
var stringify = require('rehype-stringify')
var doc = require('rehype-document')

unified()
  .use(parse)
  .use(mutate)
  .use(doc, {title: 'Hi!'})
  .use(stringify)
  .process(vfile.readSync('./README.org'), function (err, file) {
    console.error(report(err || file))
    console.log(String(file))
  })
EOF

cat > README.org <<EOF
* hello
  world
EOF

node test.js
```

results in

```
/tmp/orga-test/node_modules/oast-to-hast/lib/index.js:31
  var meta = tree.meta || {};
                  ^

TypeError: Cannot read property 'meta' of undefined
    at Function.toHAST (/tmp/orga-test/node_modules/oast-to-hast/lib/index.js:31:19)
    at freeze (/tmp/orga-test/node_modules/unified/index.js:123:28)
    at Function.process (/tmp/orga-test/node_modules/unified/index.js:360:5)
    at Object.<anonymous> (/tmp/orga-test/test.js:14:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

Would you be able to provide some updated guidance on how to set up orga for a simple org-string to html conversion?

For context, I am playing around with https://github.com/xiaoxinghu/orgajs/blob/master/packages/orga/src/inline.js to address the performance in https://github.com/xiaoxinghu/orgajs/issues/6. I don't understand the unifiedjs toolchain so I am just trying to infer the structure from `inline.js` alone. By using a character based parser and bypassing the regex for `markups` we easily get a 5x speedup, which for large files is still not fast, but no longer prohibitive.

I think another problem with the regex matching is that syntax like `/*italic-bold*/` and `*/bold-italic/*` will not get matched, although both are valid org. A stack based parser should be able to handle these, but I'm not familiar with the testing setup here, so I am looking for a way to get the rendered html.

FWIW, the parser I am using looks like this now:

```javascript
// inline.js

// after `markups` is defined
var inlineMarkups = {};
markups.forEach(function(nameMarker) {
  inlineMarkups[nameMarker.marker.replace('\\', '')] = nameMarker.name;
});

var StackParser = function(patterns) {
    var self = this;
    self.patterns = patterns;
    var ch, last_marker;
    self.parse = function(text) {

      if(Array.isArray(text)) {
        return text.reduce(function (all, node) {
          if (node.hasOwnProperty('type') && node.type != 'text') {
            return all.concat(node);
          }
          return all.concat(self.parse(node));
        }, []);
      }
      
      var string = text.value;
      var buffer = [];
      var stack = [];
      var nodes = [];
      for(var i=0; i<string.length; ++i) {
        ch = string[i];
        if(stack.length > 0) {
          last_marker = stack[stack.length-1];
        }
        if(ch == last_marker) {
          // end markup
          stack.pop();
          if(buffer.length > 0) {
            nodes.push(new _node2.default(patterns[ch], buffer.join('')));
            buffer = [];
            last_marker = null;
          }
        } else if(inlineMarkups[ch]) {
          // begin markup
          if(buffer.length > 0) {
            nodes.push(new _node2.default('text').with({ value: buffer.join('')}));
          }
          stack.push(ch);
          buffer = [];
        } else {
          buffer.push(ch);
        }
      }
      if(buffer.length > 0) {
        nodes.push(new _node2.default('text').with({ value: buffer.join('')}));
      }
      return nodes;
    };
  };

...

    for (var _iterator = markups[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
      var _ref = _step.value;
      var name = _ref.name;
      var marker = _ref.marker;
      // bypass the old parser
      break
      _loop(name, marker);
    }
    var inlineparser = new StackParser(inlineMarkups);
    text = inlineparser.parse(text);    
```

I don't know if it emits the AST correctly. It works for trivial cases, but it breaks for example URLs (slashes become italics). Currently I am comparing the result of hast -> [hiccup](https://github.com/weavejester/hiccup) using an ad-hoc converter from a clojurescript environment, so the testing is tricky. FYI, my converter code is [here](https://github.com/whacked/wksymclj/blob/master/src/cljs/wksymclj/codec/org_mode.cljs#L904-L949), but the unified stuff is magic to me. That is why I'm trying the minimal example.

**Comment by whacked** [comment]
Got it to work. Here's the minimum working example:

```javascript
const unified = require('unified')
const parse = require('orga-unified')
const mutate = require('orga-rehype')
const stringify = require('rehype-stringify')

let processor = unified()
  .use(parse)
  .use(mutate)
  .use(stringify);

let input = '* hello\nworld';
let output = processor.processSync(input);
console.log(String(output))
```

**Comment by xiaoxinghu** [comment]
Thanks for the detailed info. The example project was old, I actually copied it over from unified.js documentation. But it was outdated. Just updated it with the latest example. Please look at the project `examples/example`. Or the doc [here](https://xiaoxinghu.github.io/orgajs/with_unified/).
